### ISSUE TITLE
List subscriber delete modal Enhancement

### ISSUE THREAD

**Issue by AshiqKiron** [weMail/wemail#100]
List->Delete subscriber displays a modal [screenshot](https://imgur.com/8W59ugP) the modal 
title should be - _Are you sure to delete?_  
and text should be - _Selected subscribers will also be deleted from other lists’_
More spacing should be applied around the texts

The styling/spacing should be similar to this - [Screenshot](https://imgur.com/XoLUdlq)

**Comment by jayontasarkar** [comment]
#Resolved
