### ISSUE TITLE
Stop digest email when plugin is deactivated

### ISSUE THREAD

**Issue by AshiqKiron** [weMail/wemail#103]
I'm still getting daily digest mail from one of my email lists from my website when I've disabled and deleted the plugin from my site. We should stop sending emails when a user deactivate the plugin.

**Comment by tareq1988** [comment]
Also, we shouldn't send digest emails if nothing happened. Like this event, no change happened. 

![image](https://user-images.githubusercontent.com/153669/78638404-cf0c8b00-78de-11ea-88e5-c2564d34e940.png)
