### ISSUE TITLE
WP 5.5 Rest error

### ISSUE THREAD

**Issue by dovy** [weMail/wemail#141]
`register_rest_route was called incorrectly. The REST API route definition for wemail/v1/mailpoet/meta-fields is missing the required permission_callback argument. For REST API routes that are intended to be public, use __return_true as the permission callback. Please see Debugging in WordPress for more information. (This message was added in version 5.5.0.)`

I've had the same thing to fix in all my code, hah.

**Comment by AshiqKiron** [comment]
HI Dovy, Thank you for taking the time to report the issue. We'll look into it to fix.
