### ISSUE TITLE
Allow users to customize email contacts shown in a single page

### ISSUE THREAD

**Issue by reachmazharul** [weMail/wemail#276]
By default, weMail shows a certain number of email contacts on a single page. For example, on the single list page, twenty contacts can shows. If that list has a large number of contacts like three thousand or more, then it will be a bit hard to manage those three thousand emails. 

In this case, it will be very helpful if an option like "Show Contacts Per page" available on the plugin. From where the user with the right capability can choose whether the page should show twenty contacts or two hundred contacts.

**Comment by tareq1988** [comment]
Not important.
