### ISSUE TITLE
Unsubscribe link not working

### ISSUE THREAD

**Issue by jagganagari** [weMail/wemail#287]
Hi,
The unubscribe link in the email campaign template is not working. It is not working in any template. I enrolled for $9 per month plan as I have 5K customers. When a user clicks on unsubcribe link in the email it is simply reloading the campaign.
Please assist.

thanks

**Comment by ehsanulabrar** [comment]
Hi @jagganagari,

We are sorry that you had to face such inconvenience. This can be quickly fixed. While configuring an email campaign, navigate to the template **editing** page, edit the **template footer** and replace the shortcode `[links:unsubscribe text="click here to unsubscribe"]` with `[links:unsubscribe text="click here to unsubscribe"]`. This should fix the unsubscribe issue.

**Comment by saiftheboss7** [comment]
Should be fixed
