### ISSUE TITLE
Ask for reviews from the plugin

### ISSUE THREAD

**Issue by tareq1988** [weMail/wemail#293]
After installing the plugin, after a few days (maybe 1 week), we should ask the user to leave a review.

## Triggers

There maybe two types of triggers:

1. **Time based triggers**: Maybe after using for more than 1 week.
1. **Value based triggers**: Maybe after sending 3 campaigns, we can ask for review.

## Example: 

![image](https://freemius.com/blog/wp-content/uploads/2015/05/mashshare-review-notice.png)

**Comment by tarif-ul-haque** [comment]
@tareq1988 Bhaiya, if you approve we can create something like this for the free users

![skitch (16)](https://user-images.githubusercontent.com/79304817/160771085-a2362b56-64b9-42da-98a6-e705aad3a6b0.png)

**Comment by tareq1988** [comment]
Yes, similar design, but a little bit nicer. For everyone, free and paid users.

**Comment by tareq1988** [comment]
@sumaisa-mou here's the [example code](https://github.com/weDevsOfficial/dokan/blob/develop/includes/Admin/Notices/PluginReview.php) from Dokan

**Comment by sumaisa-mou** [comment]
Noted with thanks vaia.

> @sumaisa-mou here's the [example code](https://github.com/weDevsOfficial/dokan/blob/develop/includes/Admin/Notices/PluginReview.php) from Dokan
