### ISSUE TITLE
[FEATURE] When uploading importing a list, offer subscriber's state

### ISSUE THREAD

**Issue by saiftheboss7** [weMail/wemail#312]
## 🎨 Mockup
https://whimsical.com/importing-Dua7Sdcx5KBRy1NfLgMhwf

## Specs

When users import a CSV file - show a few more options before the list gets processed. 

This includes the option to

- Override Subscription Status
- Update the list's customers' Subscription Status
- Choose Segment

## Override Existing Subscriber Status
If users' turn this on - existing subscribers' status would be changed as per the selection made
**Infotip text:** Turn on the toggle to update the subscribers' status even if it already exists
<img width="271" alt="CleanShot 2022-08-10 at 17 45 57@2x" src="https://user-images.githubusercontent.com/19363738/183893330-2f3f4047-7692-486b-a716-bdd244e94fd7.png">

## Subscriber Status
Show all the subscription status fields here so users can choose
![CleanShot 2022-08-10 at 17 40 12@2x](https://user-images.githubusercontent.com/19363738/183892361-132e671b-e327-4a28-8d26-bb29c0cfe1d8.png)

![CleanShot 2022-08-10 at 17 58 37](https://user-images.githubusercontent.com/19363738/183895585-91ae0f0b-8b00-478f-b41c-4e5bb483c87a.png)

## Segments
User should be able to choose the segments while importing the list
![CleanShot 2022-08-10 at 17 59 51](https://user-images.githubusercontent.com/19363738/183895785-4bf675ef-5f44-436b-8983-ca1aa75b0eb0.png)

## Tags
User should be able to choose tags while importing the list
![CleanShot 2022-08-10 at 18 28 53](https://user-images.githubusercontent.com/19363738/183901284-f9ed1cef-09d0-4372-b842-e7e3216681eb.png)

**Comment by mehedimi** [comment]
I think overriding subscription status may cause some issues. @tareq1988 vai could you please take look at this issue and give us some feedback?

**Comment by tareq1988** [comment]
@mehedimi we could give an option override it, no problem.

**Comment by mehedimi** [comment]
@saiftheboss7 Segment is automated based on the subscriber's data. We can't add or remove subscribers from any segment manually.

**Comment by saiftheboss7** [comment]
^ Ok. Let's add tags then. So we can create segments after importing contacts with tags

**Comment by mehedimi** [comment]
Which tags? Are MailChimp tags need to be imported or weMail's tags assigned to subscribers while importing it?

**Comment by saiftheboss7** [comment]
No. If I important a CSV file with tags in them, it should automatically place those tags to those customers while importing those customers

**Comment by saiftheboss7** [comment]
![CleanShot 2022-08-25 at 17 22 44](https://user-images.githubusercontent.com/19363738/186651638-7db1f69c-5ee2-4e1c-bca4-fd77b4837e72.png)

Check the specs again please. I should be manually add tags to the contacts that I'm importing via CSV

**Comment by mehedimi** [comment]
So, I think you are trying to say that, user could select one or more tags from weMail while importing subscribers. And those selected tags will attach to each subscriber? Right?

**Comment by saiftheboss7** [comment]
^ Yes. @mehedimi bhai

**Comment by mehedimi** [comment]
All importers (except CSV) have **Import subscribers with {Provider} list**, which means you could check the lists and weMail will first create the lists and then import them into the newly created list.

For example, Here weMail first creates `Demo List` and `Lists Name` and then imports subscribers into it.
So, In that case, what will be happen? 
<img width="445" alt="image" src="https://user-images.githubusercontent.com/10108409/186656722-02c88068-f5a7-4c26-aa9e-8d9cd1a64ab2.png">
