### ISSUE TITLE
[Bug] Deprecation Warnings in Stringy Library

### ISSUE THREAD

**Issue by anik-fahmid** [weMail/wemail#345]
**Description:** 

Following deprecation warnings related to the Stringy library while using the weMail plugin are observed.

**Steps to Reproduce:**

- Install the latest version of the weMail plugin.
- Observe the PHP error logs or the console when using the plugin.

**Expected Behavior:**
No deprecation warnings related to the Stringy library should be displayed.

**Actual Behavior:**
Deprecation warnings are shown, indicating that certain methods in the Stringy library are using deprecated return types.

**Screenshot:**
![image](https://github.com/weMail/wemail/assets/18075711/a85f44cd-7c20-45d8-8e54-399c329d345f)

**Slack Thread:** https://wedevs.slack.com/archives/G69HSF5HB/p1704040448324299

**Comment by tareq1988** [comment]
@saiftheboss7 This is causing serious issues on all the sites. The log file is full with this error. Assign someone to fix it ASAP.

**Comment by saiftheboss7** [comment]
@sumaisa-mou Apu - we need to do a hotfix to fix this issue. Please take care of it In Sha Allah

**Comment by saiftheboss7** [comment]
Should now be fixed
