### ISSUE TITLE
I am unable to start configuring the weMail plugin.

### ISSUE THREAD

**Issue by thigas88** [weMail/wemail#72]
I am unable to start configuring the weMail plugin.

An error is occurring while accessing the plugin page:

401 Unauthorized-
HTTP API Transport: curl
DNS Resolution Time: 0.0003
Connection Time: 0.0371
Transfer Start Time (TTFB): 0.2110
Response Size: 98 B
Response Content Type: application / json
IP Address: 104.27.160.132

In my wordpress installation the x-api-key variable is empty.

![error-wemail](https://user-images.githubusercontent.com/704549/69459854-7b473e00-0d51-11ea-8e2d-c3b8f6f92ba0.PNG)

**Comment by tareq1988** [comment]
Is your site online or it's a local site?

**Comment by thigas88** [comment]
> Is your site online or it's a local site?

My site is online at https://easygreja.com.br/

**Comment by tareq1988** [comment]
Are you using any plugin that's blocking the REST API? Seems [like it is](https://easygreja.com.br/wp-json/).

weMail is heavily depended on REST API.

**Comment by thigas88** [comment]
> Are you using any plugin that's blocking the REST API? Seems [like it is](https://easygreja.com.br/wp-json/).
> 
> weMail is heavily depended on REST API.

When I am logged in wordpress the api response is active.

**Comment by thigas88** [comment]
There is an error accessing the getwemail api.

When wordpress requests https://api.getwemail.io/v1/settings/general an error 401 is being generated
![error-api](https://user-images.githubusercontent.com/704549/69562384-d2d1ed80-0f8d-11ea-8b57-85554e88d14b.PNG)

**Comment by thigas88** [comment]
How is weMail API Authentication done? All requests are accusing without access

![image](https://user-images.githubusercontent.com/704549/69562694-76230280-0f8e-11ea-96e1-e8ab5cabf1bf.png)

**Comment by thigas88** [comment]
On debug function get in includes/Core/Api/Api.php header content **x-api-key** is NULL

![image](https://user-images.githubusercontent.com/704549/69563356-b59e1e80-0f8f-11ea-8c97-cb2b502f3963.png)




`string(44) "https://api.getwemail.io/v1/settings/general" array(1) { ["headers"]=> array(1) { ["x-api-key"]=> NULL } }`
